### ISSUE TITLE
Networking and Design Patterns shouldn't be optional.

### ISSUE THREAD

**Issue by gnusosa** [jwasham/google-interview-university#33]
From what I recall, in my two attempts to join Google, I've found their guides mentioning, as part of reading material, the [TCP/IP_Illustrated](https://en.wikipedia.org/wiki/TCP/IP_Illustrated) series, specifically, Vol 2 & 3. Aside from that, remarks from ex-Googlers, touch on reading about Design Patterns, specifically, the [Gang Of Four book](https://en.wikipedia.org/wiki/Design_Patterns).

I would add their recently released [SRE book](https://landing.google.com/sre/) and the [Unix Administration Handbook](https://www.pearsonhighered.com/program/Nemeth-UNIX-and-Linux-System-Administration-Handbook-4th-Edition/PGM105967.html), since it's known to be Unix and OS admin questions from time to time.

Have a great day.

**Comment by jwasham** [comment]
Thanks, Carlos,
I'm trying to get a recent copy of the candidate coaching notes and will update from there. I want to make sure that I don't tell folks more than what Google prescribes as required knowledge for the interview.

There are thousands of possible questions that could be asked in the interview, and that's why the supplemental material is there. I'm the type who will overprepare, as you can tell, so I reviewed/read all of it, which is why it has taken me months of full-time study. In my opinion, the supplemental material consists of things all software engineers should have some familiarity with to be successful in their role, except for some more obscure things such as van Emde Boas trees.

I'll add those books to the list. 

Were you going for a software engineer role or SRE?

**Comment by gnusosa** [comment]
I have done both, and at both times, I've found that knowing how Google works internally, and how they developed their services around their infrastructure helps a lot with predicting questions about any implementation you might suggest. If any interviewee finds a rabbit hole they can latch on, they will go on. For instance, this has happened multiple times to other friends applying, they lacked the networking knowledge or Unix skills, and the interviewer kept on asking and going down that rabbit hole of knowledge that the interviewee lacked. Which is completely valid from a Interviewer stand of point, when you develop services or components they usually interact with the Network or a Unix infra.

**Comment by Jahhein** [comment]
@jwasham I highly recommend the github repo java-design-patterns for resource information to add to your own repo here. If you use it, check the issues list. Iluwatar has links to various websites that he pulls pattern concepts from.

https://github.com/iluwatar/java-design-patterns

**Comment by acerjp0514** [comment]
Hey this is my first opening on this repository issue, so yeah I'm John and I'm here in Maui Hawaii. I have Google account and it's exciting opportunity to have a helper on letting me have more knowledge on PHP program and Python script language. I love it because it's so much fun challenging to learn a difficult script and I'm getting more and more in to knowing all the best way to PHP, Python programming language. So is there a way for me to get a sample of problem on scripting to test my capabilities of I am capable to make it work. Yeah I'm unemployed but I have a Chromebook to study for PHP, Python that way I can find a way to find a job on what I am learning from my chrome and Android devices.

**Comment by jwasham** [comment]
Welcome @acerjp0514 
There are a few books with interview problems listed in the project, like Programming Interviews Exposed and Cracking the Coding interview, but the examples are all C, C++, C#, or Java.
To get practice/exercises to get better with PHP or Python, check out http://exercism.io/languages
It's free, too.

**Comment by jwasham** [comment]
I've heard back from my contact at Google, and I'm making updates to the project.
