### ISSUE TITLE
My Getting Started with DigitalOcean Guide

### ISSUE THREAD

**Issue by it-sumanp** [jwasham/google-interview-university#73]
if-else.in/cloud/getting-started-with-digitalocean/

**Comment by it-sumanp** [comment]
follow link to get seven month free DO Cloud service

**Comment by andrewfonseca** [comment]
Nice. Thanks!

**Comment by raj-maurya** [comment]
Thanks @it-sumanp

**Comment by rohit-numato** [comment]
**Warning**: I'm not sure whether Digital Ocean guide is actually relevant to joining google or not (and not to mention that the guide linked above has no real "Getting started" section, just signup, nothing that any person trying for Google doesn't already know).
The guide posted by above commentator contains **referral link** of his own account. Considering `high popularity` of this repository, and the fact that the 'guide' will certainly fail because applying 2 coupons at same time is not allowed by Digital Ocean, and you have to nudge their customer support crying foul about less credits received, this `Issue` posted by the above user seems purely opportunistic and money-making activity.

**Comment by it-sumanp** [comment]
Sorry if you think so ..
I can remove it if it is of no use to community .

**Comment by jwasham** [comment]
Declining this issue.
